"use strict";
exports.__esModule = true;
var Libro_1 = require("./Libro");
var GestorDeLibros_1 = require("./GestorDeLibros");
var libro1 = new Libro_1.Libro("Cuando no queden más estrellas que contar", "María Martínez", "Novela", 2021, "Cross Books");
var libro2 = new Libro_1.Libro("Bajo un cielo Blanco", " Elizabeth Kolbert", "Ensayo", 2021, "Crítica");
var libro3 = new Libro_1.Libro("El amor en los tiempos del cólera", "Gabriel García Márquez", "Novela", 1985, "La Oveja Negra Ltda");
var libro4 = new Libro_1.Libro("La Divina comedia", "Dante Alighieri", "Epopeya", 1321, "Greenbookseditore");
var libro5 = new Libro_1.Libro("El lobo estepario", "Herman Hesse", "Novela", 1927, "Negret Books");
var libro6 = new Libro_1.Libro("El asesinato de Platón", "Marcos Chicot", "Misterio", 2020, "Planeta");
var biblioteca = new GestorDeLibros_1.GestorDeLibros("Biblioteca: ");
biblioteca.agregarLibro(libro1);
biblioteca.agregarLibro(libro2);
biblioteca.agregarLibro(libro3);
biblioteca.agregarLibro(libro4);
biblioteca.agregarLibro(libro5);
console.log(biblioteca.toString());
var arreglo = biblioteca.getLibros();
arreglo.push(libro6);
var biblioteca_2 = new GestorDeLibros_1.GestorDeLibros("Biblioteca 2: ", arreglo);
console.log(biblioteca_2.toString());
